### ISSUE TITLE
Exercise 3: stretch exercise for extra credits

### ISSUE THREAD

**Issue by mobileraj** [tycebrown/super-basic-stopwatch#4]
Deploy Exercise 2 Flask code to Google Cloud Platform. Choose any option available to deploy to flask app and then send me a URL to test the  app.

If you are unable to do it, document the steps you were able to do and which ones you got stuck at.

**Comment by tycebrown** [comment]
@mobileRaj Here is the url: [https://flask-stretch-158854745372.us-central1.run.app/](https://flask-stretch-158854745372.us-central1.run.app/)

**Comment by mobileraj** [comment]
@tycebrown thank you!. can you do a quick writeup in markdown in the repo of the steps you took to deploy it so others can try as well?
BTW we are confirmed for 10:30 AM meeting with team at Fairfield Marriott in Rolla on Friday
